// pages/index.vue
<template>
  <EContainer class="main">
    <ECard>
      <div class="wrapper">
        <div class="avatar">
          <picture>
            <source :srcset="$applyCDN('/images/avatars/amzrk2_256p.webp')" type="image/webp" />
            <source :srcset="$applyCDN('/images/avatars/amzrk2_256p.jpg')" type="image/jpeg" />
            <img :src="$applyCDN('/images/avatars/amzrk2_256p.jpg')" />
          </picture>
        </div>
        <div class="content">
          <span class="name">DSRKafuU</span>
          <span class="id">amzrk2</span>
          <div class="ctrl">
            <EButton
              v-for="icon of icons"
              :key="icon.name"
              size="2.5rem"
              :href="icon.link"
              target="_blank"
            >
              <Icon :i="icon.icon" />
            </EButton>
          </div>
        </div>
      </div>
    </ECard>
  </EContainer>
</template>

<script>
export default {
  data() {
    return {
      icons: [
        { name: 'Blog', icon: 'blog', link: 'https://blog.amzrk2.cc' },
        { name: 'GitHub', icon: 'github', link: 'https://github.com/amzrk2' },
        { name: 'Twitter', icon: 'twitter', link: 'https://twitter.com/amzrk2' },
        { name: 'Bangumi', icon: 'tv', link: 'https://bgm.tv/user/amzrk2' },
        { name: 'Steam', icon: 'steam', link: 'https://steamcommunity.com/id/amzrk2/' },
      ],
    };
  },
};
</script>

<style>
.main .wrapper {
  display: flex;
  height: 12.5rem;
}

.main .avatar {
  flex: 0 0 auto;
  width: 12.5rem;
  height: 100%;
  display: flex;
  justify-content: flex-end;
  align-items: center;
  padding-right: 1rem;
}

.main .avatar img {
  display: block;
  width: 8rem;
  height: 8rem;
  border-radius: 50%;
  background-color: var(--color-wrapper);
}

.main .content {
  flex: 1 0 auto;
  padding: var(--space-lg);
  padding-left: 0;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

.main .content .name {
  font-size: var(--font-lg);
  font-weight: 500;
  letter-spacing: 0.025rem;
  margin-top: var(--space-sm);
}

.main .content .id {
  font-size: var(--font-sm);
  margin-top: var(--space-sm);
}

.main .content .ctrl {
  margin-top: var(--space-base);
}

@media screen and (max-width: 524px) {
  .main .wrapper {
    display: flex;
    flex-direction: column;
    height: unset;
  }

  .main .avatar {
    width: 100%;
    height: 12rem;
    display: flex;
    justify-content: center;
    align-items: center;
    padding-right: 0;
  }

  .main .avatar img {
    display: block;
    width: 8rem;
    height: 8rem;
    border-radius: 50%;
    background-color: var(--color-wrapper);
  }

  .main .content {
    padding-top: 0;
    padding-left: var(--space-lg);
  }

  .main .content .name {
    margin-top: 0;
  }

  .main .content .id {
    font-size: var(--font-sm);
    margin-top: var(--space-sm);
  }

  .main .content .ctrl {
    margin-top: var(--space-base);
  }
}
</style>

// pages/index.tsx
import type { GetServerSideProps } from 'next';

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  return {
    props: {
      cookies: req.headers.cookie || '',
    },
  };
};

import styles from './index.module.scss';
import {
  Card,
  Flex,
  Heading,
  Text,
  IconButton,
  ButtonGroup,
  useColorModeValue,
} from '@chakra-ui/react';
import Image from 'next/image';
import {
  FaBlog,
  FaCompactDisc,
  FaGithub,
  FaSteam,
  FaTwitter,
} from 'react-icons/fa';
import SakanaWidget from '../components/SakanaWidget';
import { reportClick } from '../utils/analytics';
import avatarImage from '../assets/dsrkafuu_1280p.jpg';
import Head from 'next/head';

function Home() {
  const cardBg = useColorModeValue('white', 'whiteAlpha.300');

  return (
    <>
      <Head>
        <title>DSRKafuU</title>
        <meta name='description' content='Internet for people, not profit' />
      </Head>
      <SakanaWidget />
      <Card
        bg={cardBg}
        position='fixed'
        left='50%'
        top='50%'
        transform='translate(-50%, -50%)'
        py={{ base: '7', md: '6' }}
        w={{ base: '260px', md: '440px' }}
      >
        <Flex
          justify='center'
          align='center'
          direction={{ base: 'column', md: 'row' }}
        >
          <Image
            className={styles.image}
            width={128}
            height={128}
            src={avatarImage}
            alt='Avatar'
            priority
          />
          <Flex
            direction='column'
            justify='center'
            align='center'
            ml={{ base: '0', md: '4' }}
            mt={{ base: '4', md: '0' }}
          >
            <Heading size='lg'>DSRKafuU</Heading>
            <Text mt='1'>Internet for people, not profit</Text>
            <ButtonGroup spacing='0.5' mt='1'>
              <IconButton
                as='a'
                size='sm'
                variant='ghost'
                icon={<FaBlog />}
                aria-label='Blog'
                onClick={(e) => reportClick('goto_blog', e)}
                href='https://blog.dsrkafuu.net/'
                target='_blank'
              />
              <IconButton
                as='a'
                size='sm'
                variant='ghost'
                icon={<FaGithub />}
                aria-label='GitHub'
                onClick={(e) => reportClick('goto_github', e)}
                href='https://github.com/dsrkafuu'
                target='_blank'
              />
              <IconButton
                as='a'
                size='sm'
                variant='ghost'
                icon={<FaTwitter />}
                aria-label='Twitter'
                onClick={(e) => reportClick('goto_twitter', e)}
                href='https://twitter.com/dsrkafuu'
                target='_blank'
              />
              <IconButton
                as='a'
                size='sm'
                variant='ghost'
                icon={<FaCompactDisc />}
                aria-label='Bangumi'
                onClick={(e) => reportClick('goto_bgm', e)}
                href='https://bgm.tv/user/dsrkafuu'
                target='_blank'
              />
              <IconButton
                as='a'
                size='sm'
                variant='ghost'
                icon={<FaSteam />}
                aria-label='Steam'
                onClick={(e) => reportClick('goto_steam', e)}
                href='https://steamcommunity.com/id/dsrkafuu/'
                target='_blank'
              />
            </ButtonGroup>
          </Flex>
        </Flex>
      </Card>
    </>
  );
}

export default Home;
